sudo: required

language: java
jdk:
  - oraclejdk8

services:
  - docker

env:
 global:	
  - mssql_jdbc_test_connection_properties='jdbc:sqlserver://localhost:1433;databaseName=master;username=sa;password=<YourStrong!Passw0rd>;'
  - mssql_jdbc_logging='true'
  # Enabling logging with console / file handler for JUnit Test Framework. 
  #- mssql_jdbc_logging_handler='console'|'file'

install: 
  - ps: Write-Host 'Installing JCE with powershell'
  - ps: cd AppVeyorJCE
  - ps: choco pack
  - ps: choco install jce -fdv -s . -y -failonstderr
  - ps: cd..
  - ps: mkdir AE_Certificates
  - ps: cd AE_Certificates
  - ps: $cert = New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -dnsname testcert.petri.com
  - ps: $pwd = ConvertTo-SecureString -String "password" -Force -AsPlainText
  - ps: $path = 'cert:\localMachine\my\' + $cert.thumbprint
  - ps: $certificate = Export-PfxCertificate -cert $path -FilePath cert.pfx -Password $pwd
  - ps: Get-ChildItem -path cert:\LocalMachine\My > certificate.txt
  - ps: keytool -importkeystore -srckeystore $certificate -srcstoretype pkcs12 -destkeystore clientcert.jks -deststoretype JKS -srcstorepass password -deststorepass password du 2> $null 
  - ps: cd..
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild41
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild42

before_script:
  - docker pull microsoft/mssql-server-linux
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=<YourStrong!Passw0rd>' -p 1433:1433 -d microsoft/mssql-server-linux

script: 
  - docker ps -a
  
##Test for JDBC Specification 41 & 42 and submit coverage report.
  - mvn test -B -Pbuild41 jacoco:report && bash <(curl -s https://codecov.io/bash) -cF JDBC41
  - mvn test -B -Pbuild42 jacoco:report && bash <(curl -s https://codecov.io/bash) -cF JDBC42

#after_success:
# instead of after success we are using && operator for conditional submitting coverage report.
#  - bash <(curl -s https://codecov.io/bash)
