version: '{build}'

environment:
  mssql_jdbc_test_connection_properties: jdbc:sqlserver://localhost:1433;instanceName=SQL2016;databaseName=master;username=sa;password=Password12!;
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0 

services:
  - mssql2016
  
install:
  - ps: Write-Host 'Installing JCE with powershell'
  - ps: cd AppVeyorJCE
  - ps: choco pack
  - ps: choco install jce -fdv -s . -y -failonstderr
  - ps: cd..
  - ps: New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -dnsname orin.windowsitpro.internal
  - ps: $pwd = ConvertTo-SecureString -String "password" -Force -AsPlainText
  - ps: cd AE_Certificates
  - ps: Export-PfxCertificate -cert cert:\localMachine\my\CE0976529B02DE058C9CB2C0E64AD79DAFB18CF4 -FilePath cert.pfx -Password $pwd

build_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild41
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild42
test_script:
  - mvn test -B -Pbuild41
  - mvn test -B -Pbuild42
