version: '{build}'

environment:
  mssql_jdbc_test_connection_properties: jdbc:sqlserver://localhost:1433;instanceName=SQL2016;databaseName=master;username=sa;password=Password12!;
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0 

services:
  - mssql2016
  
install:
  - ps: Write-Host 'Installing JCE with powershell'
  - ps: cd AppVeyorJCE
  - ps: choco pack
  - ps: choco install jce -fdv -s . -y -failonstderr
  - ps: cd..
  - ps: mkdir AE_Certificates
  - ps: cd AE_Certificates
  - ps: $cert = New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -dnsname testcert.petri.com
  - ps: $pwd = ConvertTo-SecureString -String "password" -Force -AsPlainText
  - ps: $path = 'cert:\localMachine\my\' + $cert.thumbprint
  - ps: $certificate = Export-PfxCertificate -cert $path -FilePath cert.pfx -Password $pwd
  - ps: Get-ChildItem -path cert:\LocalMachine\My > certificate.txt
build_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild41
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild42
test_script:
  - mvn test -B -Pbuild41
  - mvn test -B -Pbuild42
  
